#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/4desk/4desk /usr/bin/4desk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/4desk.service ]; then
			rm /etc/systemd/system/4desk.service /usr/lib/systemd/system/4desk.service /usr/lib/systemd/user/4desk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/4desk/files/systemd/4desk.service /usr/lib/systemd/system/4desk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload 4desk.service: Unit 4desk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/4desk.service:10: Executable path is not absolute: pkill -f "4desk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/4desk.service
		fi
		systemctl daemon-reload
		systemctl enable 4desk
		systemctl start 4desk
	fi
fi
